const imageMap = {
  // Root question
  "root:Where do you want to go?": "game-dashboard.webp",
  "root:Hello! are you a boy or a girl?": "game-dashboard.webp",
  "root:How many siblings you have?": "game-dashboard.webp",
  "root:what scares you the most?": "game-dashboard.webp",
  "root:What is your favorite color?": "game-dashboard.webp",
  // Beach branch
  Beach: "beach.webp",
  "Beach:What do you want to do on the beach?": "beach.webp",
  "Build a sandcastle": "sandcastle.webp",
  "Go swimming": "swimming.webp",
  "Play beachball": "beach.webp",
  "Beach:What do you want to build?": "sandcastle.webp",
  "Build a house": "sandcastle.webp",
  "Build a castle": "sandcastle.webp",
  "Build a statue": "sandcastle.webp",
  "Beach:Who do you want to build it with?": "sandcastle.webp",
  "Build alone": "alone-beach.webp",
  "Build with friends": "with-friends-beach.webp",
  "Build with parents": "with-parent-beach.webp",
  "Beach:What kind of swimming?": "swimming.webp",
  "Put your feet on the shore": "shore.webp",
  Swim: "swimming.webp",
  "Surf with friends": "surf.webp",
  "Beach:Who do you want to swim with?": "swimming.webp",
  Alone: "swim-alone.webp",
  "With friends": "friends.webp",
  "Beach:Who do you want to play with?": "beachball.webp",
  "Play with the ball alone": "alone.webp",
  "Play with family": "with-parent-beach.webp",
  "Play with other kids": "friends.webp",
  // Mountain branch
  Mountain: "mountain.webp",
  "Mountain:What do you want to do on the mountain?": "mountain.webp",
  "Discover the hidden cave": "cave.webp",
  "Hike to the top": "hike.webp",
  "Ride the arial lift": "arial-lift.webp",
  "Mountain:Which direction do you want to go?": "cave.webp",
  "Go left to the open area": "open-area.webp",
  "Go right to the narrow cave": "narrow-cave.webp",
  "Mountain:You see the blue sky. What do you want to do?": "open-area.webp",
  "Want to get out": "exit-cave.webp",
  "Want to discover the other direction": "narrow-cave.webp",
  "Mountain:You find a big spider. How do you feel?": "spider.webp",
  Fear: "spider-fear.webp",
  Exciting: "spider-exciting.webp",
  "Mountain:What do you want to do?": "mountain.webp",
  "Get out": "exit-cave.webp",
  "Discover the other direction": "narrow-cave.webp",
  "Mountain:What do you want to do next?": "hike.webp",
  "Look at the landscapes": "landscape.webp",
  "Ride the arial left down": "arial-lift-down.webp",
  "Hike down": "hike-down.webp",
  // City branch
  City: "city.webp",
  "City:What do you want to do in the city?": "city.webp",
  "Go shopping": "shopping.webp",
  "Go to the park": "park.webp",
  "Go to the factory": "factory.webp",
  "City:Where do you want to go?": "shopping.webp",
  "Go to the arcade": "arcade.webp",
  "Go to the toy store": "toy-store.webp",
  "Shopping with parents": "shopping-parents.webp",
  "City:Who are you playing with?": "arcade.webp",
  "Play alone": "arcade-alone.webp",
  "Play with friends": "arcade-friends.webp",
  "City:Pick a toy?": "toy-store.webp",
  "A truck": "truck.webp",
  "A doll": "doll.webp",
  "A scooter": "scooter.webp",
  "City:What happened?": "shopping-parents.webp",
  "Buy something for yourself": "buy-item.webp",
  "Don’t buy something for yourself": "no-buy.webp",
  "City:Where do you want to go?_park": "park.webp",
  "Go to the playground": "playground.webp",
  "Sit and watch the sky": "sky-park.webp",
  "Talk to the kid across the path": "kid-path.webp",
  "City:What do you want to do?_playground": "playground.webp",
  "Play on the swing": "swing.webp",
  "Play on slides": "slides.webp",
  "City:With whom?": "playground.webp",
  Alone_playground: "play-alone.webp",
  "With a friend": "play-friend.webp",
  "City:What do you do next?": "kid-path.webp",
  "Go play with him on the playground": "playground-friend.webp",
  "Make friends and watch the sky": "sky-friends.webp",
  "City:What do you want to do?_factory": "factory.webp",
  "Go on a factory tour": "factory-tour.webp",
  "Watch a movie across the street": "movie.webp",
  // Space branch
  Space: "spaceship.webp",
  "Space:Where do you want to go?": "spaceship.webp",
  "Go left to the main cabin": "main-cabin.webp",
  "Go right": "right-corridor.webp",
  "Look at the window": "space-window.webp",
  "Space:Who do you talk to?": "main-cabin.webp",
  "Talk to the captain": "captain.webp",
  "Talk to the captain's daughter": "captain-daughter.webp",
  "Space:What do you tell him?": "captain.webp",
  "Go back to earth": "earth-return.webp",
  "Discover new planets": "new-planets.webp",
  "Space:What do you do together?": "captain-daughter.webp",
  "Watch the sky": "space-sky.webp",
  "Go on a little spaceship": "small-spaceship.webp",
  "Space:What do you want to do?_right": "right-corridor.webp",
  "Talk to the girl": "space-girl.webp",
  "Pet the dog": "space-dog.webp",
  "Space:What do you feel?": "space-window.webp",
  Fear_space: "space-fear.webp",
  Awe: "space-awe.webp",
  "Space:What do you want to do?_window": "space-window.webp",
  "Talk to parents": "space-parents.webp",
  Breathe: "space-breathe.webp",
};

export default imageMap;